{% set version = "1.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcompendium
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rcompendium_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rcompendium/rcompendium_{{ version }}.tar.gz
  sha256: f46dd3409511eb7fe1b2e9408fb327ea90d04a6b3ebb7b17ac9053143dfc4224

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cffr
    - r-cli
    - r-codemetar
    - r-devtools
    - r-gert
    - r-gh
    - r-gtools
    - r-renv
    - r-rmarkdown
    - r-rstudioapi
    - r-stringr
    - r-usethis
    - r-xfun
  run:
    - r-base
    - r-cffr
    - r-cli
    - r-codemetar
    - r-devtools
    - r-gert
    - r-gh
    - r-gtools
    - r-renv
    - r-rmarkdown
    - r-rstudioapi
    - r-stringr
    - r-usethis
    - r-xfun

test:
  commands:
    - $R -e "library('rcompendium')"           # [not win]
    - "\"%R%\" -e \"library('rcompendium')\""  # [win]

about:
  home: https://frbcesab.github.io/rcompendium/
  dev_url: https://github.com/FRBCesab/rcompendium/
  license: GPL-2.0-or-later
  summary: 'Makes easier the creation of R package or research compendium (i.e. a predefined files/folders structure) so that users can focus on the code/analysis instead of wasting time organizing files. A full ready-to-work structure is set up with some additional features: version control, remote repository creation,
    CI/CD configuration (check package integrity under several OS, test code with ''testthat'', and build and deploy website using ''pkgdown''). This package heavily relies on the R packages ''devtools'' and ''usethis'' and follows recommendations made by Wickham H. (2015) <ISBN:9781491910597> and Marwick B. et al. (2018)
    <doi:10.7287/peerj.preprints.3192v2>.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - giancarlodigi
